### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by Webmasterei** [byjord/Magento-AMP#1]
Hi,
a customer was asking about AMP and I'm sniffing around to see what has been done so far. Your Readme doesn't say a lot. How far are you and is this - in any way -  ready for production? 

What happens if customers want to add something to the cart? Is the user then pushed to regular magento?  

Thanks for anwering.

Bernhard

**Comment by byjpr** [comment]
Hi @Webmasterei 

AMP is a great project at the minute but the boost that Google is giving to a site's that support AMP seems only to be for news articles at the moment. However this extension is in development as a future proofing concept.

I wouldn't recommend using this in production as of yet, it's around 0.0.3 in build and there are many things still to be done to it. The flow for Magento add to basket would be moving to regular Magento on click as AMP does not support any javascript outside of their own. Another possiblity would be to have a server side add to cart, but I don't see how we could do caching, or make the experience on the AMP site a good one.

Pull requests are always accepted if you'd like to get involved with the development, Bernhard.

Kindest,

**Comment by Webmasterei** [comment]
Hi byjord,
I don't know at the moment. My client was asking about it but I am not sure if he wouldn't prefer a move to mage2 first.... if he wants amp, this would be definitely a good point to start. We'll see!

**Comment by byjpr** [comment]
Hey @Webmasterei,

No problem. 

I'd still recommend staying away from M2 until the point that Magento, Inc force merchants towards the platform. Let sometimes happen so the code base can mature.
That being said, if it's only a small merchant, with relatively low risk, it might be worth moving them for your experience.

**Comment by sopedro** [comment]
Hi, how to configure this?

**Comment by byjpr** [comment]
Hi @sopedro ,

Sorry I'm not providing support for the extension. It's here as an example of what is possible.

If you'd like to explore this more, I'd suggest reaching out to Magento Agency.
