### ISSUE TITLE
Publish on AMPThemes.io

### ISSUE THREAD

**Issue by cborodescu** [byjord/Magento-AMP#2]
Hey Jordan!

This is Ciprian from AMPThemes.io - a market place for AMP themes. I noticed your Magento-AMP on GitHub and I wanted to ask if it would be OK with you to publish it on AMPThemes.io as a freebie, mentioning you as an author and all. Looking forward to hearing your thoughts.

**Comment by byjpr** [comment]
Hey @cborodescu,

Sure, please go ahead.

How do updates work for AMPThemes.io? I'm planning on making some updates in the coming months to the package.
